// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sessionInit.ts";

const manifest = {
  "actions": {
    "app-vtex-session/actions/sessionInit.ts": $$$$$$$$$0,
  },
  "name": "app-vtex-session",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
