// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/myAction.ts";
import * as $$$$$$$$$1 from "./actions/sessionInit.ts";
import * as $$$0 from "./loaders/myLoader.ts";
import * as $$$$$$0 from "./sections/mySection.tsx";

const manifest = {
  "loaders": {
    "app-vtex-session/loaders/myLoader.ts": $$$0,
  },
  "sections": {
    "app-vtex-session/sections/mySection.tsx": $$$$$$0,
  },
  "actions": {
    "app-vtex-session/actions/myAction.ts": $$$$$$$$$0,
    "app-vtex-session/actions/sessionInit.ts": $$$$$$$$$1,
  },
  "name": "app-vtex-session",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
